<?php ob_start();?>
    <div class="text-center">
        <h1>Programme télé </h1>
        <h2><?php echo(date("l d M Y"))?></h2>
        <hr>
    </div>
    <div class="container">
        <div class="heure_filtre text-center">
            <!--On donne la possibilité de saisir l'heure pour filtrer l'affichage du programme télé-->
            <span>Saisissez l'heure pour laquelle vous souhaitez avoir le programme télé :</span>    
            <input  type="time" name="heure" id="heure">
            <button class="btn btn-primary">Filtrer</button>
        </div>
        <hr>
        <?php foreach($pageFill['indoor'] as $programme) { ?>   <!--On va parcourir la liste contenant les programmes de chaque chaîne
                                                                On va afficher la chaîne, le programme ainsi que l'heure de début et de fin et le synopsis-->
            <ul>
                <?php for($i=0;$i<sizeof($programme['program']);++$i) {?>
                    <li> 
                        <strong><?=$programme['channel']?></strong> 
                        <?=$programme['program'][$i]['title']?>
                        <?=$programme['program'][$i]['begin']?>
                        <?=$programme['program'][$i]['end']?>
                        <br>
                        <em>Synopsis : <?=$programme['program'][$i]['synopsis']?> </em>
                    </li>
                <?php } ?>
            </ul>
            <br>
        <?php } ?>
    </div>
    <script>
        (function($){
            $("button").click(function(){
                heureFiltre = $(this).siblings('#heure')[0].value
            });
        })(jQuery);

    </script>


<?php $sectionContent=ob_get_clean();