<!DOCTYPE html>
<html lang="fr">

<head> 
<meta charset="UTF-8">
<title>Connexion</title>

</head>

<body>

    <section>
        
        <?php{?>
            <div>
                <input type="text" name="username" placeholder="Nom d'utilisateur">
                <input type="text" name="password" placeholder="Mot de passe">
                <a href="page">Connexion</a>
            </div>

            <div>
                <p>Pas encore inscrit ?</p>
                <a href="registration.phtml">S'inscrire</a>
            </div>
    </section>

</body>
