<?php ob_start();?>
    <div class="row">
        <form class="col-md-12" method="post" action="index.php?page=recherche" id="plats">
            <select class="custom-select col-md-3" name="type" size=1> <!--Liste déroulante des types de plats (entrées,desserts...)-->
                <?php foreach($pageFill['type'] as $type) { ?>
                    <option><?=$type?>
                <?php } ?>
            </select>
            <input class="col-md-3 form-control" type="text" name="search" placeholder="Rechercher des recettes">
            <input class="col-md-3 btn btn-primary" type="submit" class="buttonNav" value="Rechercher">
        </form>
    </div>
    <br>
    <article class="recette">
        <div classe="col-md-12">
            <div class="row" id="rec">
                <div class="col-md-12" id="nom_recette">
                    <h1 ><?=$pageFill['recipe'][0]['titre']?></h1>
                    <img src="<?=$pageFill['recipe'][0]['picture']?>" alt="Image recette">
                </div>
            </div>
            <br>
            <div class="row" id="times">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12" id="timeGlobal">
                            Temps total : <?=$pageFill['recipe'][0]["globalTime"]?> min
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-6" id="timePrep">
                            Temps de préparation : <?=$pageFill['recipe'][0]['prepTime']?> min
                        </div>
                        <div class="col-md-6" id="timeCook">
                            Temps de cuisson : <?=$pageFill['recipe'][0]['cookTime']?> min
                        </div>
                    </div>
                </div>
            </div>
            <hr>    
                
            <div class="row">
                <div class="col-md-12">
                    <p><?=$pageFill['recipe'][0]['steps']?></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <p class="note">Note :</p>
                </div>
                <div class="col-md-4">
                    <p class="difficulty">Difficulté :</p>
                </div>
                <div class="col-md-4">
                    <p class="price">Budget :</p>
                </div>
            </div>
        </div>
    </article>
    <br>
    <article class="row">
        <div class="col-md-6" id="ingredients_recette">
            <h1>Liste des ingrédients nécessaires pour la recette</h1> <!--A mettre à jour au clic sur le bouton "Je réalise cette recette"-->
            <div class="row">
                <p>Nombre de personnes : </p>
                <form method="post" action="index.php?page=cooking">
                    <input type="text" name="eaternumber" placeholder="">
                </form>
            </div>
            <div class="row">
                
                    <div class="col-md-3">
                        <p>J'ai besoin de : </p>
                    </div>
                    <div class="col-md-3">
                        <p>J'achète : </p>
                    </div>
            </div>
            <div class="row">
                    <ul>
                        <?php for($j=0;$j<sizeof($pageFill['recipe'][0]['items']);++$j) { ?> <!--On parcourt la liste des ingrédients de la recette sélectionnée par l'utilisateur-->
                                <li>
                                    <?=$pageFill['recipe'][0]['items'][$j]['quantity']?> <?=$pageFill['recipe'][0]['items'][$j]['name']?> <!--(<?=$nombre?> manquant(s))-->
                                </li> <!--On affiche les ingrédients avec leur quantité correspondante-->
                        <?php } ?>

                    </ul>
                    
                        <ul>
                            <?php for($j=0;$j<sizeof($pageFill['recipe'][0]['items']);++$j) { ?> <!--On parcourt la liste des ingrédients de la recette sélectionnée par l'utilisateur-->
                                <li>
                                    <form method="post" action="index.php?page=cooking">
                                            <input type="text" name="itemnumber" placeholder="">    
                                    </form>
                                    </li> <!--On affiche les ingrédients avec leur quantité correspondante-->
                                <?php } ?>

                        </ul>
                    <br>
                    
                    
                
            </div>
            
        </div>
    
        <div class="col-md-6" id="possession">
            <h1>Liste possession</h1>    
            <div class="row">
                <ul>
                    <!--<?php foreach($pageFill['have'] as $have) { ?>
                        <li><?=$have['quantity']?><?=$have['items']?> (<?=$nombre?> restant(s) après la recette)</li>
                    <?php } ?>-->
                </ul>
            </div>
            <div class="row">
                <div class="col-md-12" id="prepBouton">
                    <form method="post" action="index.php?page=cooking">
                        <input class="btn btn-success" type="submit" value="Je prépare">
                    </form>
                </div>
            </div>
        </div>
    </article>
<?php $sectionContent=ob_get_clean();