<?php ob_start();?>
    <div class="col-lg-12 text-center">
        <h1>Chercher une recette</h1>
        <hr>
    </div>
    <div class="d-flex justify-content-center">
        <form class="w-100 row" method="post" action="index.php?page=cooking" id="plats"><!-- partie recherche seule -->
            <select class="custom-select col-lg m-3" name="type" size=1> <!--Liste déroulante des types de plats (entrées,desserts...)-->
                <?php foreach($typeList as $type) { ?>
                    <option><?= $type->getLabel() ?>
                <?php } ?>
            </select>
            <input require class="col-lg form-control m-3" type="text" name="search" placeholder="Nom de recette">
            <input class="col-lg btn btn-primary m-3 buttonNav" type="submit" value="Rechercher">
        </form>
    </div>
    
    <article class="recette">
        <div classe="col-md-12 text-center">
            <div class="d-flex justify-content-center my-3"><h1 id="nom_recette"><?=$pageFill['recipe'][0]['titre']?></h1></div>
            <div class="d-flex justify-content-center"><img class="col-lg-3" src="<?=$pageFill['recipe'][0]['url']?>" alt="Image recette"></div>
            
            <div class="row my-4" id="times">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12" id="timeGlobal">
                            Temps total : <?=$pageFill['recipe'][0]["globalTime"]?> min
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6" id="timePrep">
                            Temps de préparation : <?=$pageFill['recipe'][0]['prepTime']?> min
                        </div>
                        <div class="col-md-6" id="timeCook">
                            Temps de cuisson : <?=$pageFill['recipe'][0]['cookTime']?> min
                        </div>
                    </div>
                </div>
            </div>
            <hr>    
            <div class="row text-center">
                <div class="col-md-4 mt-3">
                    <p class="note">Note :</p>
                </div>
                <div class="col-md-4 mt-3">
                    <p class="difficulty">Difficulté :</p>
                </div>
                <div class="col-md-4 mt-3">
                    <p class="price">Budget :</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md text-center">
                    <h2>Etapes de préparation :</h2>    
                    <p><?=$pageFill['recipe'][0]['steps']?></p>
                </div>
                <div class="col-md text-center">
                    <h2>Liste des ingrédients :</h2> <!--A mettre à jour au clic sur le bouton "Je réalise cette recette"-->
                    <ul>
                        <?php for($j=0;$j<sizeof($pageFill['recipe'][0]['items']);++$j) { ?> <!--On parcourt la liste des ingrédients de la recette sélectionnée par l'utilisateur-->
                        <li class="my-1 align-middle list_ingredient">
                            <?=$pageFill['recipe'][0]['items'][$j]['quantity']?> <?=$pageFill['recipe'][0]['items'][$j]['name']?> <!--(<?=$nombre?> manquant(s))-->
                        </li> <!--On affiche les ingrédients avec leur quantité correspondante-->
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
    </article>
<?php $sectionContent=ob_get_clean();