
<?php ob_start();?>
    <div class="recherche">
        <form method="post" action="index.php?page=exercices"> <!--On réalise ici le champ texte, le bouton pour rechercher ainsi que la liste déroulante des muscles qu'il est possible de travailler afin de filtrer les exercices-->
            <input type="text" placeholder="Rechercher exercice">
            <input type="submit" class="buttonNav" value="Rechercher">
            <select name="Muscle" size=1>
                <option>Ici parcourir la liste de tous les muscles possibles : il faut la créer pour tous les regrouper
            </select>
        </form>
    </div>
    
    <ul> <!--On liste ici tous les exercices avec la possibilité de les ajouter à la séance d'entraînement-->
        <?php foreach($pageFill['exercice'] as $exercice) { ?>
            <li>
                <article>
                    <h1><?=$exercice['name']?></h1>
                    Image
                    <form method="post" action="index.php?page=exercices">
                        <input type="submit" class="buttonNav" value="Ajouter"> <!--Le bouton permettant d'ajouter l'exercice à la séance-->
                    </form>
                </article>
            </li>
        <?php } ?>
    </ul>

    <aside>
        <h1>Séances d'entraînement</h1>
        <form method="post" action="index.php?page=exercices">
            <input type="submit" class="buttonNav" value="Nouvelle séance"> <!--Le bouton permettant de créer une nouvelle séance-->
            <input type="submit" class="buttonNav" value="Supprimer séance"> <!--Le bouton permettant de supprimer une séance-->
        </form>
        <ul>
            <?php for($i=1;$i<=sizeof($pageFill['seance']);++$i) { ?>    <!--On liste les séances-->
                <li>
                    <div class="seance">
                        <h1>Séance <?=$i?></h1>   <!--A regarder combien de séance sont enregistrées pour l'utilisateur puis ajuster-->
                        <ul>
                            <?php for($j=0;$j<sizeof($pageFill['seance'][$i-1]['exercices']);++$j) { ?> <!--On liste les exercices associés à la séance-->
                                <li>
                                    <?=$pageFill['seance'][$i-1]['exercices'][$j]['name']?> <!--Nom + image des exercices donc cette ligne = à modifier-->
                                    <?=$pageFill['seance'][$i-1]['exercices'][$j]['image']?>
                                </li>
                            <?php } ?>
                        </ul>
                        <form method="post" action="index.php?page=exercices">
                            <input type="submit" class="buttonNav" value="Modifier séance"> <!--Le bouton permettant de modifier une séance-->
                            <input type="submit" class="buttonNav" value="Réaliser séance"> <!--Le bouton permettant d'indiquer que l'utilisateur réalise la séance-->
                        </form>
                    </div>
                </li>
            <?php } ?>
        </ul>
    </aside>
<?php $sectionContent=ob_get_clean();
