<?php ob_start(); ?>
    <div class="col-lg-12 text-center">
        <h1>Votre état de santé</h1>
        <hr>
    </div>
    <article class="container">
        <div class="row w-100 graph-container">
            <div class="col-lg-8 graphes my-2">
                <h2 class="my-2">Graphique santé</h2>
                <canvas id="graph"></canvas>

                <div class="d-flex justify-content-center my-2">
                    <div class="row w-100">
                        <button class="col-lg mx-2 btn btn-primary" id="weightChart">Poids</button>
                        <button class="col-lg mx-2 btn btn-primary" id="sleepChart">Temps de sommeil</button>
                        <button class="col-lg mx-2 btn btn-primary" id="caloryChart">Calories ingérées</button>
                    </div>   
                </div>
            </div>
            <div class="offset-lg-1 col-lg-3 saisie my-2">
                <h2 class="my-2">Aujourd'hui</h2>
                <br>
                <form method="post" action="index.php?page=health">
                    <label for="sleepTime">Heures de sommeil</label>
                    <input required type="time" class="form-control" name="sleepTime">
                    <br>
                    <label for="weight">Poids</label>
                    <input required type="number" class="form-control" name="weight" step=".1">
                    <br>
                    <div>
                        <input class="btn btn-success" type="submit" value="Enregistrer">
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </article>
    
    <br>
    <div class="container">
        <table class="table table-bordered text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Informations</th>
                    <th scope="col">Commentaire</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <?php if (isset($imc)) { ?>
                        <td>
                            Votre IMC est de <strong><?= number_format(floatval($imc), 1) ?></strong>
                        </td>
                        <td>
                            <?= htmlspecialchars($commIMC) ?>
                        </td> 
                    <?php } 
                    else { ?>
                        <td colspan="2">
                            Veuillez renseigner votre taille dans votre profil et votre poids du jour pour connaître votre IMC.
                        </td>
                    <?php } ?>
                </tr>
                <tr> 
                    <?php if (isset($commDiff)) { ?>
                        <td>
                            Pour votre taille, le poids idéal est de : <strong><?= $lorentzWeigth ?>kg.</strong>
                        </td>
                        <td>
                        <?= isset($commDiff) ? htmlspecialchars($commDiff) : 'Entrez votre poids du jour pour plus d\'information' ?>

                        </td>
                    <?php } 
                    else { ?>
                        <td colspan="2">
                            Veuillez renseigner votre taille et votre sexe dans votre profil pour connaître votre poids idéal.
                        </td>
                    <?php } ?>
                    
                </tr>
                <tr>
                    <?php if (isset($commSleepTod)) { ?>
                        <td>
                            Vous avez dormi 
                            <?= htmlspecialchars($listHealth !== false && $listHealth[0]->getSleep() != null ? intval(explode(':',$listHealth[0]->getSleep())[0])."h".explode(':',$listHealth[0]->getSleep())[1] : '') ?>
                            cette nuit
                        </td>
                        <td>
                            <?= htmlspecialchars($commSleepTod) ?>
                        </td>
                    <?php } 
                    else { ?>
                        <td colspan="2">
                            Veuillez renseigner votre date de naissance dans votre profil et vos heures de sommeil du jour pour plus d'information.
                        </td>
                    <?php } ?>
                </tr>
                <tr>
                    <?php if (isset($temps_moyen)) { ?>
                        <td>
                            Vous avez dormi en moyenne <?= htmlspecialchars($temps_moyen) ?> au cours des 7 derniers jours
                        </td>
                        <td>
                            <?= htmlspecialchars($commRythme) ?>
                        </td>
                    <?php }
                    else { ?>
                        <td colspan ="2">
                            Veuillez renseigner vos heures de sommeil du jour pour plus d'information.
                        </td>
                    <?php } ?>
                </tr>

            </tbody>
        </table>
    </div>
    <script>
        var variableRecuperee = <?= $data ?>;
        var userDate = []
        var userWeight = []
        var userSleep = []
        var userCalory = []

        if(!$.isEmptyObject(variableRecuperee)) {
            for (var i = 0; i < variableRecuperee.length; i++) {
                variableRecuperee[i] = JSON.parse(variableRecuperee[i])
                
                splitedDate = variableRecuperee[i]._recordDate.split("-")
                userDate.push(splitedDate[2] + "/" + splitedDate[1] + "/" + splitedDate[0])

                userWeight.push(parseFloat(variableRecuperee[i]._weight))

                splitedSleep = variableRecuperee[i]._sleep.split(":")
                userSleep.push(parseFloat(splitedSleep[0] + "." + String(parseInt(splitedSleep[1]) * 100 / 60)))
                
                userCalory.push(parseFloat(variableRecuperee[i]._calories))
            }
        }

        var config = {
            type: 'line',
            data: {
                labels: userDate,
                datasets: [{
                    label: 'Poids par jour',
                    data: userWeight,
                    borderColor: [
                        'rgba(0, 0, 0, 1)'
                    ],
                    borderWidth: 1,
                    backgroundColor: [
                        'rgba(0, 0, 0, 0)'
                    ],
                    pointBackgroundColor: 'rgba(0, 0, 0, 1)',
                    pointBorderColor: 'rgba(0, 0, 0, 0)'
                    
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'black'
                    }
                }
            }
        };

        window.onload = function() {
			var ctx = document.getElementById('graph').getContext('2d');
			window.myLine = new Chart(ctx, config);
		};
        
        document.getElementById('weightChart').addEventListener('click', function(){
            config.data.datasets.forEach(function(dataset) {
                dataset.label = 'Poids par jour';
				dataset.data = userWeight;
			});

            window.myLine.update()
        });

        document.getElementById('sleepChart').addEventListener('click', function(){
            config.data.datasets.forEach(function(dataset) {
                dataset.label = 'Temps de sommeil par jour';
				dataset.data = userSleep;
			});

            window.myLine.update()
        });
        
        document.getElementById('caloryChart').addEventListener('click', function(){
            config.data.datasets.forEach(function(dataset) {
                dataset.label = 'Calories ingérées par jour';
				dataset.data = userCalory;
			});

            window.myLine.update()
        });         

    </script>

<?php $sectionContent = ob_get_clean();