<?php ob_start(); ?>
    <div class="col-lg-12 text-center">
        <h1>Votre état de santé</h1>
        <hr>
    </div>

    <article class="container">
        <div class="row w-100 graph-container">
            <div class="col-lg-8 graphes my-2">
                <h2 class="my-2">Graphique santé</h2>
                <canvas id="graph"></canvas>

                <div class="d-flex justify-content-center my-2">
                    <div class="row w-100">
                        <button class="col-lg mx-2 btn btn-primary" id="weightChart">Poids</button>
                        <button class="col-lg mx-2 btn btn-primary" id="sleepChart">Temps de sommeil</button>
                        <button class="col-lg mx-2 btn btn-primary" id="caloryChart">Calories ingérées</button>
                    </div>   
                </div>
            </div>
            <div class="offset-lg-1 col-lg-3 saisie my-2">
                <h2 class="my-2">Aujourd'hui</h2>
                <br>
                <form method="post" action="index.php?page=health">
                    <label for="sleepTime">Heures de sommeil</label>
                    <input required type="time" class="form-control" name="sleepTime">
                    <br>
                    <label for="weight">Poids</label>
                    <input required type="number" class="form-control" name="weight" step=".1">
                    <br>
                    <div>
                        <input class="btn btn-success" type="submit" value="Enregistrer">
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </article>
    
    <br>
    
    <div class="row tab">
        <div class="col-lg-8 ">
            <table class="table table-dark table-bordered text-center">
                <thead>
                    <tr>
                        <th scope="col">Informations</th>
                        <th scope="col">Commentaire</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php if (isset($imc)) { ?>
                            <td>
                                Votre IMC est de <strong><?= htmlspecialchars(isset($imc) ? number_format (floatval($imc), 1) : '') ?></strong> <!--On va ici afficher l'IMC puis des messages différents selon l'IMC de l'utilisateur-->
                            </td>

                            <td>
                                <?= htmlspecialchars(isset($commIMC) ? $commIMC : '') ?>
                            </td> 
                            
                        <?php } 
                        else { ?>
                            <td colspan="2">
                                Veuillez entrer votre poids dans pour pouvoir calculer votre IMC.
                            </td>
                        <?php } ?>
                    </tr>
                    <tr> 
                        <?php if (isset($commDiff)) { ?>
                            <td>
                                Pour votre taille, le poids idéal est de : <strong> < calcul en js avec taille et sexe > kg.</strong>
                            </td>
                            <td>
                            <?= htmlspecialchars(isset($commDiff) ? $commDiff : '') ?>

                            </td>
                        <?php } 
                        else { ?>
                            <td colspan="2">
                                Veuillez entrer votre taille en cliquant sur mon profil. 
                            </td>
                        <?php } ?>
                        
                    </tr>
                    <tr>
                        <?php if (isset($commSleepTod)) { ?>
                            <td>
                                Vous avez dormi 
                                <?= htmlspecialchars($listHealth !== false && $listHealth[0]->getSleep() != null ? intval(explode(':',$listHealth[0]->getSleep())[0]) : '') ?>
                                heures cette nuit
                            </td>
                            <td>
                                <?= htmlspecialchars(isset($commSleepTod) ? $commSleepTod : '') ?>
                            </td>
                        <?php } 
                        else { ?>
                            <td colspan="2">
                                Veuillez entrer vos heures de sommeil de cette nuit.
                            </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <?php if (isset($temps_moyen)) { ?>
                            <td>
                                Vous avez dormi en moyenne <?= htmlspecialchars(isset($temps_moyen) ? $temps_moyen : '') ?> au cours des 7 dernier jours
                            </td>
                            <td>
                                <?= htmlspecialchars(isset($commRythme) ? $commRythme : '') ?>
                            </td>
                        <?php }
                        else { ?>
                            <td colspan ="2">
                                Veulliez entrer vos heures de sommeil.
                            </td>
                        <?php } ?>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
    <script>
        var variableRecuperee = <?= json_encode($listHealth) ?>;
        console.log(variableRecuperee)
        
        var config = {
            type: 'line',
            data: {
                labels: ['12/06/2020', '13/06/2020', '14/06/2020', '15/06/2020', '16/06/2020', '17/06/2020',],
                datasets: [{
                    label: 'Poids par jour',
                    data: [60, 62, 63, 65, 62, 63],
                    borderColor: [
                        'rgba(0, 0, 0, 1)'
                    ],
                    borderWidth: 1,
                    backgroundColor: [
                        'rgba(0, 0, 0, 0)'
                    ],
                    pointBackgroundColor: 'rgba(0, 0, 0, 1)',
                    pointBorderColor: 'rgba(0, 0, 0, 0)'
                    
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'black'
                    }
                }
            }
        };

        window.onload = function() {
			var ctx = document.getElementById('graph').getContext('2d');
			window.myLine = new Chart(ctx, config);
		};
        
        document.getElementById('weightChart').addEventListener('click', function(){
            config.data.datasets.forEach(function(dataset) {
                dataset.label = 'Poids par jour';
				dataset.data = [60, 62, 63, 65, 62, 63];
			});

            window.myLine.update()
        });

        document.getElementById('sleepChart').addEventListener('click', function(){
            config.data.datasets.forEach(function(dataset) {
                dataset.label = 'Temps de sommeil par jour';
				dataset.data = [7, 8, 9, 6, 5, 9];
			});

            window.myLine.update()
        });
        
        document.getElementById('caloryChart').addEventListener('click', function(){
            config.data.datasets.forEach(function(dataset) {
                dataset.label = 'Calories ingérées par jour';
				dataset.data = [2000, 2300, 2100, 1990, 1880, 2310];
			});

            window.myLine.update()
        });         

    </script>

<?php $sectionContent = ob_get_clean();