<?php ob_start(); ?>
    <div class="text-center">
        <h1>Bienvenue sur Your Everyday Sunshine !</h1>
        <hr>
    </div>
    <?php 
        $first = true;
        foreach($grid as $line) { ?>
        <div class="row <?= $first ? 'mt-4' : '' ?>">
            <?php 
                $first = false;
                foreach($line as $card) { ?>
                <div class="col-lg">
                    <div class="card bg-light mb-3 <?= !$card["active"] ? 'inactive' : '' ?>">
                        <div class="text-center <?= !$card["active"] ? 'card-header nonehr' : 'card-header' ?>">
                            <a class="col-lg mt-2 " href="<?= $card["active"] ? 'index.php?page='.$card["link"] : 'index.php?page=profile#'.($card["link"]=="health"? 'height':'town') ?>">
                                <img alt="icon" src="resource/image/<?= htmlspecialchars($card["link"]) ?>.png"/>
                                <button class="btn btn-link">
                                    <h2 class="mb-0">
                                        <?= htmlspecialchars($card["display"]) ?><br>
                                    </h2>
                                </button>
                            </a>
                        </div>
                        <div class="card-body">
                        <?php if(!$card["active"]){ ?>
                                <p class="inval">Veuillez renseigner votre <?=htmlspecialchars($card["missing"])?> dans votre profil</p>
                            <?php } 
                            else { ?>
                                <?php switch ($card["link"]) {
                                    case "sport":?>
                                        <div class="text-center">
                                            <h4 class="cart-title"><?= htmlspecialchars($sport->getLabel()) ?></h4>
                                            <img alt="img_sport" src="<?= htmlspecialchars($sport->getPicture()) ?>" width="40%"/>
                                        </div>
                                        <br>
                                        Retrouvez plus d'exercices dans ce module.
                                    <?php break; 
        
                                    case "health":?>
                                        <h4 class="cart-title">Votre suivi de santé</h4>
                                        <p class="card-text">
                                            Votre poids idéal est de <?= htmlspecialchars($lorentzWeight) ?>kg.
                                            <br><br>
                                            Retrouvez un suivi de votre état de santé à travers votre activité sur ce site et les informations que vous avez renseignés.
                                        </p>
                                    <?php break;
        
                                    case "news":?>
                                        <h4 class="cart-title"><a href="<?= htmlspecialchars($news->getURL()) ?>"><?= htmlspecialchars(\ForceUTF8\Encoding::toUTF8(strtoupper($news->getTitle()))) ?></a></h4>
                                        <p class="card-text">
                                            <?= htmlspecialchars(\ForceUTF8\Encoding::toUTF8($news->getSummary())) ?>
                                            <br><br>
                                            Retrouvez plus d'actualités résumées dans ce module.
                                        </p>
                                    <?php break;
        
                                    case "weather": ?>
                                        <h4 class="cart-title">Météo de <?= $weather->getTown()->getLabel() ?></h4>
                                        <p class="card-text">
                                            Il fait actuellement <?= intval($weather->getFeltTemp()) ?>°C à <?= htmlspecialchars($weather->getTown()->getLabel())?>
                                            <br>
                                            Etat du ciel : <?= htmlspecialchars($weather->getSky()->getLabel()) ?>
                                            <br>
                                            <br>
                                            Retrouvez plus en détails la météo de la semaine dans ce module.
                                        </p>
                                    <?php break;
        
                                    case "activities":
                                        if ($activities != false) { ?>
                                            <h4 class="cart-title">
                                                Aujourd'hui, regardez <?='"'.htmlspecialchars(\ForceUTF8\Encoding::toUTF8($activities->getTitle())).' "' ?> 
                                                à <?= intval(explode(':',$activities->getBegin())[0])."h".explode(':',$activities->getBegin())[1] ?> 
                                                sur <?= htmlspecialchars(\ForceUTF8\Encoding::toUTF8($activities->getChannel()->getLabel())) ?>
                                            </h4>
                                        <?php } else echo("Pas de programme dans l'heure."); ?>
                                        <p class="card-text">
                                            Retrouvez plus en détails le programme du jour dans ce module.
                                        </p>
                                    <?php break;
        
                                    case "cooking": ?>
                                        <h4 class="cart-title">Recette proposée : <?= htmlspecialchars(\ForceUTF8\Encoding::toUTF8($cooking->getName())) ?></h4>
                                        <p class="card-text"> 
                                            Vous ne savez pas quoi cuisiner pour ce soir ? Consultez notre recette de <?= htmlspecialchars(\ForceUTF8\Encoding::toUTF8($cooking->getName())) ?> et dégustez un bon plat
                                            <br>
                                            <br>
                                            Retrouvez plus en détails cette recette ou une autre dans ce module.
                                        </p>
                                    <?php break;
                                    
                                } ?>
                            <?php } ?>
                        </div>   
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
<?php $sectionContent = ob_get_clean();
