<?php ob_start(); ?>
    <h1 class="col-lg mt-4 mb-4">Page d'Accueil</h1>
    <hr>
    <?php 
        $first = true;
        foreach($grid as $line) { ?>
        <div class="row <?= $first? 'mt-4' : '' ?>">
            <?php foreach($line as $card) { ?>
                <a class="col-lg mt-2" href="index.php?page=<?= $card["link"] ?>">
                    <button class="col-lg-12 btn btn-primary"><?= $card["display"] ?></button>
                </a>
            <?php } ?>
        </div>
    <?php 
        $first = false;
        } ?>
<?php $sectionContent = ob_get_clean();
