<?php ob_start(); ?>    
    <div class="text-center">
        <h1>Connexion</h1>
        <hr>
    </div>
    <div class="d-flex justify-content-center">
        <div class="mt-4 col-lg-3">
            <form method="post" action="index.php?user=login">
                <p> 
                    <label for="username" class="ml-1">Nom d'utilisateur</label><br>
                    <input required type="text" class="form-control" name="username" placeholder="Nom d'utilisateur" value="<?= isset($trustedPost['name']) ? htmlspecialchars($trustedPost['name']) : '' ?>">
                    <br>
                    <label for="password" class="ml-1">Mot de passe</label><br>
                    <input required type="password" class="form-control" name="password" placeholder="Mot de passe" value="<?= isset($trustedPost['password']) ? htmlspecialchars($trustedPost['password']) : '' ?>">
                </p>
                <br>
                <p class="d-flex justify-content-center">
                    <input type="submit" class="btn btn-success" value="Connexion"/>
                </p>
            </form>
            <br>
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <p>Pas encore inscrit ?</p>
                    <a class="btn btn-primary" href="index.php?user=register" role="button">S'inscrire</a>
                </div>
            </div>
        </div>
    </div>
<?php $sectionContent=ob_get_clean();
