
<?php ob_start();?>
    <form method="post" action="index.php?user=login">
    <p>
        <label for="username">Nom d'utilisateur</label><br>
        <input type="text" name="username" placeholder="Nom d'utilisateur" required>
        <br><br>
        <label for="password">Mot de passe</label><br>
        <input type="text" name="password" placeholder="Mot de passe" required>
        
    </p>
    <br><br>
    <input type="submit" value="Connexion">
    <div>
        <p>Pas encore inscrit ?</p>
        <a href="index.php?user=register">S'inscrire</a>
    </div>
    
<?php $sectionContent=ob_get_clean();
