<?php ob_start();?>
    <div class="text-center">
        <h1 class="text-center">Tenez vous informés de l'actualité en un coup d'oeil !</h1> 
        <hr>
    </div>
    <article>
        <div class="container"> 
            <?php foreach ($articleList as $article) { ?>
                <div class="card bg-light p-0 my-4 text-center">
                    <div class="card-header">
                        <a href="<?= htmlspecialchars($article->getURL()) ?>"><?= htmlspecialchars(\ForceUTF8\Encoding::toUTF8(strtoupper($article->getTitle()))) ?></a>
                        <p class="mb-0">Temps de lecture aproximatif de l'article : 
                        <?php
                            $tmp = explode(':',$article->getReadingTime());
                            $m = intval($tmp[1]);
                            $s = intval($tmp[2]);
                        
                            echo($m > 0 ? htmlspecialchars($m)." min " : '');
                            echo($m > 0 && $s > 0 ? " et " : '');
                            echo($s > 0 ? htmlspecialchars($s)." sec" : '');
                        ?>                                
                    </div>
                    <p class="p-3">
                        <?= htmlspecialchars(\ForceUTF8\Encoding::toUTF8($article->getSummary())) ?>
                    </p>
                </div>
            <?php } ?>
        </div>
    </article>
<?php $sectionContent=ob_get_clean();