<?php ob_start();
    if (isset($trustedPost['errMsgs'])) { ?>
        <div>
            <?php foreach($trustedPost['errMsgs'] as $errMsg) echo $errMsg; ?> <br>
        </div> 
    <?php } ?>

    <form method="post" action="index.php?user=profile">
        <div class="infos_compte">
            <h1>Informations de compte</h1>
            <div>
                <div>
                    <label for="username">Nom d'utilisateur</label><br>
                    <input type="text" name="username" placeholder="Nouveau nom" value="<?= htmlspecialchars($_SESSION['user']->getName()) ?>">
                </div>
                <!--
                <div>
                    <label for="avatar">Avatar</label><br>
                    <input type="text" name="avatar" placeholder="Nouveau nom" value="< ?= $_SESSION['user']->getName() ?>" required>
                </div>
                -->
                <div>
                    <label for="password">Mot de passe</label><br>
                    <input type="text" name="password" placeholder="Nouveau mot de passe">
                </div>
                <div>
                    <label for="passwordConf">Confirmer le mot de passe</label><br>
                    <input type="text" name="passwordConf" placeholder="Confirmer le nouveau mot de passe">
                </div>
            </div>
        </div>

        <div class="infos_perso">
            <h1>Informations personnelles</h1>
            <div>
                <div>
                    <label for="birthDate">Votre date de naissance</label><br>
                    <input type="date" name="birthDate" placeholder="Nouveau nom" value="<?= htmlspecialchars(Entity::printDate($_SESSION['user']->getBirthDate())) ?>">
                </div>
                <div>
                    <label for="height">Votre taille</label><br>
                    <input type="text" name="height" placeholder="Taille en mètre" value="<?= htmlspecialchars($_SESSION['user']->getHeight()) ?>">
                </div>
                <div>
                    <label for="town">Votre ville</label><br>
                    <input type="text" name="town" placeholder="Nouvelle ville" value="<?= htmlspecialchars($_SESSION['user']->getTown()->getLabel()) ?>">
                </div>
            </div>
        </div>

        <input class="btn btn-outline-success" type="submit" value="Modifier mes informations"/>
        <input type="hidden" name="form" value="1">
    </form>
<?php $sectionContent=ob_get_clean();

//ajouter script js pour afficher formulaire (ou champs et bouton de validation) avec un clic bouton "modifier mes données" ?