<?php ob_start(); ?>
    <div class="d-flex justify-content-center">
        <div class="col-md-6">
            <form method="post" action="index.php?user=profile">
                <div class="infos_compte">
                    <h1>Informations de compte</h1>
                    <p>
                        <label for="username">Nom d'utilisateur</label><br>
                        <input type="text" class="form-control" name="username" placeholder="Nouveau nom" value="<?= htmlspecialchars($_SESSION['user']->getName()) ?>">
                        <br>
                        <div>
                            afficher l'image, positionner bouton "changer d'avatar"
                            <label for="avatar">Avatar</label>
                            <div class="custom-file">
                                <label class="custom-file-label" for="avatar">Importer image</label>
                                <input type="file" class="custom-file-input" name="avatar" accept=".png" value="<?= isset($trustedPost['avatar']) ? htmlspecialchars($trustedPost['avatar']) : '' ?>">
                            </div>
                        </div>
                        <br>
                        <label for="password">Mot de passe</label><br>
                        <input type="password" class="form-control" name="password" placeholder="Nouveau mot de passe">
                        <br>
                        <label for="passwordConf">Confirmer le mot de passe</label><br>
                        <input type="password" class="form-control" name="passwordConf" placeholder="Confirmer le nouveau mot de passe">
                    </p>
                </div>

                <div class="infos_perso">
                    <h1>Informations personnelles</h1>
                    <p>
                        <label for="birthDate">Votre date de naissance</label><br>
                        <input type="date" class="form-control" name="birthDate" placeholder="Nouveau nom" value="<?= htmlspecialchars(Entity::printDate($_SESSION['user']->getBirthDate())) ?>">
                        <br>
                        <label for="height">Votre taille</label><br>
                        <input type="text" class="form-control" name="height" placeholder="Taille en mètre" value="<?= htmlspecialchars($_SESSION['user']->getHeight()) ?>">
                        <br>
                        <label for="town">Votre ville</label><br>
                        <input type="text" class="form-control" name="town" placeholder="Nouvelle ville" value="<?= htmlspecialchars($_SESSION['user']->getTown()->getLabel()) ?>">
                    </p>
                </div>

                <p class="d-flex justify-content-center">
                    <input type="submit" class="btn btn-outline-success" value="Modifier mes informations"/>
                    <input type="hidden" name="form" value="1">
                </p>
            </form>
<?php $sectionContent=ob_get_clean();

//ajouter script js pour afficher formulaire (ou champs et bouton de validation) avec un clic bouton "modifier mes données" ?