<?php ob_start(); ?>
        <div class="infos d-flex justify-content-center">

            <div class="col-md-6 infos_compte">
                <h1>Informations de compte</h1>
                <hr>
                <form method="post" action="index.php?user=profile">
                    <p>
                        <label for="username">Nom d'utilisateur</label><br>
                        <input type="text" class="form-control" name="username" placeholder="<?= htmlspecialchars($_SESSION['user']->getName()) ?>" value="<?= isset($trustedPost['name']) ? htmlspecialchars($trustedPost['name']) : '' ?>">
                        <br>
                        <label for="password">Mot de passe</label><br>
                        <input type="password" class="form-control" name="password" placeholder="Nouveau mot de passe">
                        <br>
                        <label for="passwordConf">Confirmer le mot de passe</label><br>
                        <input type="password" class="form-control" name="passwordConf" placeholder="Confirmer le nouveau mot de passe">
                    </p>
                    
                    <p class="d-flex justify-content-center">
                        <input type="submit" class="btn btn-outline-success" value="Modifier mes identifiants"/>
                    </p>
                <form>
            </div>
            
            <div class="col-md-6 infos_perso">
                <h1>Informations personnelles</h1>
                <hr>
                <form method="post" action="index.php?user=profile">
                    <p>
                        <div>
                            <label for="avatar">Avatar</label>
                            <br>todo : add image box here<br>
                            <input type="file" name="avatar" accept=".png">
                        </div>
                        <br>
                        <label for="birthDate">Votre date de naissance</label><br>
                        <input type="date" class="form-control" name="birthDate" value="<?= htmlspecialchars(isset($trustedPost['birthDate']) ? $trustedPost['birthDate'] : $_SESSION['user']->getBirthDate() != null ? $_SESSION['user']->getBirthDate() : '') ?>">
                        <br>
                        <label for="height">Votre taille</label><br>
                        <input type="text" class="form-control" name="height" id="height" placeholder="<?= htmlspecialchars($_SESSION['user']->getHeight())?>" value="<?= isset($trustedPost['height']) ? htmlspecialchars($trustedPost['height']) : '' ?>">
                        <br>
                        <label for="town">Votre ville</label><br>
                        <input type="text" class="form-control" name="town" id="town" placeholder="<?= htmlspecialchars($_SESSION['user']->getTown()->getLabel()) ?>" value="<?= isset($trustedPost['town']) ? htmlspecialchars($trustedPost['town']) : '' ?>">
                    </p>
                    
                    <p class="d-flex justify-content-center">
                        <input type="submit" class="btn btn-outline-success" value="Modifier mes informations personnelles"/>
                    </p>
                </form>  
            </div>
<?php $sectionContent=ob_get_clean();

//ajouter script js pour afficher formulaire (ou champs et bouton de validation) avec un clic bouton "modifier mes données" ?