<!DOCTYPE html>
<html lang="fr">

<head> 
<meta charset="UTF-8">
<title>Connexion</title>

</head>

<body>

    <section>
        
        <?php{?>
                <input type="text" name="username" placeholder="Nom d'utilisateur">
                <input type="text" name="password" placeholder="Mot de passe">
                <input type="text" name="password_conf" placeholder="Confirmer le mot de passe">
                <input type="text" name="e-mail" placeholder="Adresse mail">
                <a href="homePage.phtml">S'inscrire</a>
    </section>
    
</body>
