<?php ob_start(); ?>
    <div class="text-center">
        <h1>Inscription</h1>
        <hr>
    </div>
    <div class="d-flex justify-content-center mx-auto">
        <div class="mt-4 col-md-3">
        <div class="info_mandat">Les champs suivis de <span class="mandatory">*</span> sont obligatoires</div><br>
            <form method="post" action="index.php?user=register" enctype="multipart/form-data">
                <p>
                    <label for="username" class="ml-1">Nom d'utilisateur <span class="mandatory">*</span></label><br>
                    <input required type="text" class="form-control" name="username" placeholder="Nom d'utilisateur" value="<?= isset($trustedPost['name']) ? htmlspecialchars($trustedPost['name']) : '' ?>">
                    <br>
                    <label for="password" class="ml-1">Mot de passe <span class="mandatory">*</span></label><br>
                    <input required type="password" minlength="8" class="form-control" name="password" placeholder="Mot de passe" value="<?= isset($trustedPost['password']) ? htmlspecialchars($trustedPost['password']) : '' ?>">
                    <br>
                    <label for="passwordConf" class="ml-1">Confirmer le mot de passe <span class="mandatory">*</span></label><br>
                    <input required type="password" minlength="8" class="form-control" name="passwordConf" placeholder="Confirmer le mot de passe" value="<?= isset($trustedPost['passwordConf']) ? htmlspecialchars($trustedPost['passwordConf']) : '' ?>">
                    <br>
                    <label for="avatar" class="ml-1">Avatar</label>
                    <br>
                    <input type="file" name="avatar" accept=".png, .jpg, .jpeg, .gif">
                    <br>
                    <br>
                    <label for="birth" class="ml-1">Date de naissance</label><br>
                    <input type="date" class="form-control" name="birth" placeholder="AAAA-MM-JJ" value="<?= isset($trustedPost['birthDate']) ? htmlspecialchars($trustedPost['birthDate']) : '' ?>">
                    <br>
                    <label for="height" class="ml-1">Taille</label><br>
                    <input type="text" class="form-control" name="height" placeholder="Exemple pour 1m80 : 1.80" value="<?= isset($trustedPost['height']) ? htmlspecialchars($trustedPost['height']) : '' ?>">
                    <br>
                    <label for="town" class="ml-1">Ville</label><br>
                    <input type="text" class="form-control" name="town" placeholder="Ville" value="<?= isset($trustedPost['town']) ? htmlspecialchars($trustedPost['town']) : '' ?>">
                    <p class="bold mt-4">Votre sexe (actuel)</p>
                    <div class="text-center">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="sex" id="femme" value="femme" 
                            <?= isset($trustedPost['sex']) && $trustedPost['sex'] == "femme" ? 'checked' : '' ?>>
                            <label class="form-check-label" for="femme">Femme</label>
                        </div>
                            <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="sex" id="homme" value="homme" 
                            <?= isset($trustedPost['sex']) && $trustedPost['sex'] == "homme" ? 'checked' : '' ?>>
                            <label class="form-check-label" for="homme">Homme</label>
                        </div>
                    </div>
                </p>                        
                
                <p class="d-flex justify-content-center">
                    <input type="submit" class="btn btn-success" value="Inscription"/>
                </p>
            </form>
            <br>
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <p>Déjà inscrit ?</p>
                    <a class="btn btn-primary" href="index.php?user=login" role="button">Se connecter</a>
                </div>
            </div>
        </div>
    </div>
<?php $sectionContent=ob_get_clean();
