<?php ob_start();?>
    <div class="text-center">
        <h1>Votre séance de sport :</h1>
        <hr>
    </div>

    <div class="menu">
        <div class="d-flex justify-content-center">
            <form method="post" action="index.php?page=sport" class="row w-100 mb-0">
                <input type="hidden" name="all" value="true">
                <input type="submit" class="btn btn-info col-lg m-3" value="Tous les exercices"> 
            </form>
            <form method="post" action="index.php?page=sport" class="row w-100 mb-0"> 
                <input type="hidden" name="random" value="true">
                <input type="submit" class="btn btn-info col-lg m-3" value="Aléatoire">
            </form>
        </div>
        <hr>
        <div class="d-flex justify-content-center">
            <form class="row w-100" method="post" action="index.php?page=sport">
                <input required class="form-control col-lg m-3" type="text" name="search" placeholder="Rechercher exercice">
                <select class="custom-select col-lg m-3" name="Muscle" size=1>
                    <?php foreach ($muscleList as $muscle) { ?>
                        <option><?= $muscle->getLabel() ?></option>
                    <?php } ?>
                </select>
                <input type="submit" class="btn btn-info col-lg m-3" value="Rechercher">
            </form>
        </div>
    </div>
    <br>
    <div class="row">
        <!--Les lignes suivantes (jusqu'au "<ul>") correspondent aux exercices générés aléatoirement, donc si clic sur "Aléatoire" : il faudra donc masquer cette partie du code si clic sur liste d'exercices-->
        <div class="col-md liste_exercices text-center py-3">
            <h2 class="my-2">Liste d'exercices</h2>
            <div class="mt-4">
                <ul class="liste">
                    <?php foreach($pageFill['exercice'] as $exercice){?>   <!--On va parcourir la liste contenant les 3 exo affichés aléatoirement-->       
                        <li class="my-4">
                            <div class="d-flex justify-content-center my-3"><h4><?=$exercice['name']?></h4></div> <!--Nom + image des exercices -->
                            <div class="d-flex justify-content-center"><img alt="img_sport" href="<?=$exercice['picture']?>"/></div>
                            <p class="text-center">Calories consommées : <?=$exercice['calories']?> kcal pour 1h</p>
                            <button class="btn btn-success">Ajouter à ma séance</button>
                        </li>
                    <?php }?>
                </ul>
            </div>
        </div>
        <div class="col-md seances text-center py-3">
            <h2 class="my-2">Séance d'entraînement</h2>
            <div class="mt-4">
                <form method="post" action="index.php?page=exercices">
                    <ul class="seance">
                        <?php for($j=0;$j<sizeof($pageFill['seance'][0]['exercices']); ++$j) { ?> <!--On liste les exercices associés à la séance-->
                            <li class="my-4">
                                <input type="hidden" name="idExo" value="<?= $pageFill['seance'][0]['exercices'][$j]['id'] ?>">
                                <div class="d-flex justify-content-center my-3"><h4><?=$pageFill['seance'][0]['exercices'][$j]['name']?></h4></div> <!--Nom + image des exercices -->
                                <div class="d-flex justify-content-center"><img alt="img_sport" href="<?=$pageFill['seance'][0]['exercices'][$j]['image']?>"/></div>
                                <p class="text-center">Calories consommées : <?=$pageFill['seance'][0]['exercices'][$j]['calories']?> kcal pour 1h</p>
                                <button class="btn btn-danger">Supprimer l'exercice de la séance</button>
                            </li>
                        <?php } ?>
                    </ul>
                    <div class="d-flex justify-content-center">
                        <input type="submit" class="btn btn-info" value="Enregistrer séance">
                        <input type="submit" class="btn btn-success" value="Réaliser séance">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        (function($){
            
            $("button").click(function(){
                if($(this).hasClass('btn-success')) {
                    cloneParent = $(this).parent().clone(true, true)
                    cloneButton = cloneParent[0].children[cloneParent[0].children.length - 1]
                    
                    cloneButton.className = cloneButton.className.replace('success', 'danger')
                    $(cloneButton).text("Supprimer l'exercice de la séance")
                    cloneParent.appendTo( ".seance")
                } else if($(this).hasClass('btn-danger')){
                    $(this).parent().remove()
                }
                
            });
        })(jQuery);
    </script>
<?php $sectionContent=ob_get_clean();
