<?php ob_start();?>

    <article>

        <h1>Météo de Ville</h1>   <!--Variable à modifier, elle va correspondre au champ ville des infos de l'utilisateur-->

        <div>
            
            <div class="jour">  <!--Structure pour 1 jour. IL faut rajouter la boucle for/foreach pour le faire pour une semaine complète-->
                <h1>Jour</h1> <!--Jour selon la date-->
                <h2>Temps : <?=$pageFill['sky']?></h2>
                <p>Température min : <?=$pageFill['minTemp']?> °C </br>
                Température max : <?=$pageFill['maxTemp']?> °C </br>
                Température ressentie : <?=$pageFill['feltTemp']?> °C </br>
                Humidité : <?=$pageFill['humidity']?> % </br>
                Pression : <?=$pageFill['pressure']?> hPa </br>
                </p>
                        
            </div>


                    
        </div>

    </article>
    
<?php $sectionContent=ob_get_clean();