<?php ob_start(); ?>
    <div class="text-center">
        <h1>Météo de <?= $weatherList != false ? $weatherList[0]->getTown()->getLabel() : '' ?></h1>
        <hr>
    </div>
    <article>
        <div class="d-flex justify-content-center">
            <div class="card carte_ville">
                <div class="card-header">
                    Envie de voir la météo d'une autre ville ?
                </div>
                <br>
                <form class="d-flex justify-content-between" method="post" action="index.php?page=weather">
                    <input class="form-control mx-2" type="text" name="search" placeholder="Entrer une ville">
                    <input class="btn btn-primary mx-2" type="submit">
                </form>
                <br>
            </div> 
        </div>
        <br>
        <?php if ($weatherList != false) {
            //$i = 5;
            //foreach ($weatherList as $weather) { 
            echo('<hr><div class="row">');
            for ($i = 0; $i < count($weatherList); $i++) {
                $weather = $weatherList[$i]; ?>
                    <div class="col-lg m-3 jour card">
                        <div class="card-header">
                            <h2>
                                <?= intval(explode('-',explode(' ',$weather->getForecast())[0])[2]).'/'.
                                    explode('-',explode(' ',$weather->getForecast())[0])[1] ?>
                                <br>
                                <?= intval(explode(':',explode(' ',$weather->getForecast())[1])[0]) ?>h
                            </h2>
                        </div>
                        <br>
                        <h2>Temps : <?= $weather->getSky()->getLabel() ?></h2>
                        <br>
                        <p>
                            Température <strong>min</strong> : <?= $weather->getMinTemp() ?> °C </br>
                            Température <strong>max</strong> : <?= $weather->getMaxTemp() ?> °C </br>
                            Température <strong>ressentie</strong> : <?= $weather->getFeltTemp() ?> °C </br>
                            Humidité : <?= $weather->getHumidity() ?> % </br>
                            Pression : <?= $weather->getPressure() ?> hPa </br>
                        </p>
                    </div>
                <?php if ($i % 5 == 0 && $i != 0) { echo('</div><hr><div class="row">'); } ?>
            <?php }
            echo("</div>");
        } ?>
    </article>
    
<?php $sectionContent=ob_get_clean();