DROP TABLE IF EXISTS Sky ;
CREATE TABLE Sky (ID_sky BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_sky)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Town ;
CREATE TABLE Town (ID_town BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
MinTemp FLOAT,
MaxTemp FLOAT,
FeltTemp FLOAT,
Humidity FLOAT,
Pressure FLOAT,
ID_sky **NOT FOUND**,
PRIMARY KEY (ID_town)) ENGINE=InnoDB;

DROP TABLE IF EXISTS User ;
CREATE TABLE User (ID_user BIGINT AUTO_INCREMENT NOT NULL,
Name VARCHAR,
Password VARCHAR,
Avatar VARCHAR,
BirthDate DATE,
Height FLOAT,
town_id_town **NOT FOUND**,
PRIMARY KEY (ID_user)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Renewal ;
CREATE TABLE Renewal (ID_renewal BIGINT AUTO_INCREMENT NOT NULL,
ModuleName VARCHAR,
ID_frequency **NOT FOUND**,
PRIMARY KEY (ID_renewal)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Frequency ;
CREATE TABLE Frequency (ID_frequency BIGINT AUTO_INCREMENT NOT NULL,
NumberOfDays FLOAT,
NextDate DATETIME,
PRIMARY KEY (ID_frequency)) ENGINE=InnoDB;

DROP TABLE IF EXISTS News ;
CREATE TABLE News (ID_news BIGINT AUTO_INCREMENT NOT NULL,
Summary TEXT,
PRIMARY KEY (ID_news)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Article ;
CREATE TABLE Article (ID_article BIGINT AUTO_INCREMENT NOT NULL,
URL VARCHAR,
ReadingTime VARCHAR,
ID_news **NOT FOUND**,
PRIMARY KEY (ID_article)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Category ;
CREATE TABLE Category (ID_category BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_category)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Activity ;
CREATE TABLE Activity (ID_activity BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
Distance FLOAT,
ID_town **NOT FOUND**,
ID_category **NOT FOUND**,
PRIMARY KEY (ID_activity)) ENGINE=InnoDB;

DROP TABLE IF EXISTS TVprogram ;
CREATE TABLE TVprogram (ID_TVprogram BIGINT AUTO_INCREMENT NOT NULL,
Title VARCHAR,
Synopsis TEXT,
Begin VARCHAR,
End VARCHAR,
Genre VARCHAR,
ID_channel **NOT FOUND**,
PRIMARY KEY (ID_TVprogram)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Ingredient ;
CREATE TABLE Ingredient (ID_item BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_item)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Recipe ;
CREATE TABLE Recipe (ID_recipe BIGINT AUTO_INCREMENT NOT NULL,
Name_Recipe VARCHAR,
Picture VARCHAR,
PreparationTime VARCHAR,
CookingTime VARCHAR,
TotalTime VARCHAR,
Score_Recipe FLOAT,
Price FLOAT,
Difficulty FLOAT,
Steps TEXT,
Calories FLOAT,
ID_type **NOT FOUND**,
PRIMARY KEY (ID_recipe)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Health ;
CREATE TABLE Health (ID_health BIGINT AUTO_INCREMENT NOT NULL,
RecordDate DATE,
Weight FLOAT,
Calories FLOAT,
Sleep TIME,
ID_user **NOT FOUND**,
PRIMARY KEY (ID_health)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Sport ;
CREATE TABLE Sport (ID_sport BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
Picture VARCHAR,
Calories FLOAT,
PRIMARY KEY (ID_sport)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Muscle ;
CREATE TABLE Muscle (ID_muscle BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_muscle)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Channel ;
CREATE TABLE Channel (ID_channel BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_channel)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Type ;
CREATE TABLE Type (ID_type BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_type)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Include ;
CREATE TABLE Include (ID_recipe **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_item **NOT FOUND** NOT NULL,
Quantity FLOAT,
PRIMARY KEY (ID_recipe,
 ID_item)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Have ;
CREATE TABLE Have (ID_item **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_user **NOT FOUND** NOT NULL,
Quantity FLOAT,
PRIMARY KEY (ID_item,
 ID_user)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Work ;
CREATE TABLE Work (ID_muscle **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_sport **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_muscle,
 ID_sport)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Program ;
CREATE TABLE Program (ID_user **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_sport **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_user,
 ID_sport)) ENGINE=InnoDB;

ALTER TABLE Town ADD CONSTRAINT FK_Town_ID_sky FOREIGN KEY (ID_sky) REFERENCES Sky (ID_sky);

ALTER TABLE User ADD CONSTRAINT FK_User_town_id_town FOREIGN KEY (town_id_town) REFERENCES Town (ID_town);
ALTER TABLE Renewal ADD CONSTRAINT FK_Renewal_ID_frequency FOREIGN KEY (ID_frequency) REFERENCES Frequency (ID_frequency);
ALTER TABLE Article ADD CONSTRAINT FK_Article_ID_news FOREIGN KEY (ID_news) REFERENCES News (ID_news);
ALTER TABLE Activity ADD CONSTRAINT FK_Activity_ID_town FOREIGN KEY (ID_town) REFERENCES Town (ID_town);
ALTER TABLE Activity ADD CONSTRAINT FK_Activity_ID_category FOREIGN KEY (ID_category) REFERENCES Category (ID_category);
ALTER TABLE TVprogram ADD CONSTRAINT FK_TVprogram_ID_channel FOREIGN KEY (ID_channel) REFERENCES Channel (ID_channel);
ALTER TABLE Recipe ADD CONSTRAINT FK_Recipe_ID_type FOREIGN KEY (ID_type) REFERENCES Type (ID_type);
ALTER TABLE Health ADD CONSTRAINT FK_Health_ID_user FOREIGN KEY (ID_user) REFERENCES User (ID_user);
ALTER TABLE Include ADD CONSTRAINT FK_Include_ID_recipe FOREIGN KEY (ID_recipe) REFERENCES Recipe (ID_recipe);
ALTER TABLE Include ADD CONSTRAINT FK_Include_ID_item FOREIGN KEY (ID_item) REFERENCES Ingredient (ID_item);
ALTER TABLE Have ADD CONSTRAINT FK_Have_ID_item FOREIGN KEY (ID_item) REFERENCES Ingredient (ID_item);
ALTER TABLE Have ADD CONSTRAINT FK_Have_ID_user FOREIGN KEY (ID_user) REFERENCES User (ID_user);
ALTER TABLE Work ADD CONSTRAINT FK_Work_ID_muscle FOREIGN KEY (ID_muscle) REFERENCES Muscle (ID_muscle);
ALTER TABLE Work ADD CONSTRAINT FK_Work_ID_sport FOREIGN KEY (ID_sport) REFERENCES Sport (ID_sport);
ALTER TABLE Program ADD CONSTRAINT FK_Program_ID_user FOREIGN KEY (ID_user) REFERENCES User (ID_user);
ALTER TABLE Program ADD CONSTRAINT FK_Program_ID_sport FOREIGN KEY (ID_sport) REFERENCES Sport (ID_sport);
