DROP TABLE IF EXISTS Sky ;
CREATE TABLE Sky (ID_sky BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_sky)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Weather ;
CREATE TABLE Weather (ID_weather BIGINT AUTO_INCREMENT NOT NULL,
Forecast DATETIME,
MinTemp FLOAT,
MaxTemp FLOAT,
FeltTemp FLOAT,
Humidity FLOAT,
Pressure FLOAT,
ID_sky **NOT FOUND**,
ID_town **NOT FOUND**,
PRIMARY KEY (ID_weather)) ENGINE=InnoDB;

DROP TABLE IF EXISTS User ;
CREATE TABLE User (ID_user BIGINT AUTO_INCREMENT NOT NULL,
Name VARCHAR,
Password VARCHAR,
Avatar VARCHAR,
BirthDate DATE,
Height FLOAT,
town_id_town **NOT FOUND**,
PRIMARY KEY (ID_user)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Renewal ;
CREATE TABLE Renewal (ID_renewal BIGINT AUTO_INCREMENT NOT NULL,
ModuleName VARCHAR,
ID_frequency **NOT FOUND**,
PRIMARY KEY (ID_renewal)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Frequency ;
CREATE TABLE Frequency (ID_frequency BIGINT AUTO_INCREMENT NOT NULL,
NumberOfDays FLOAT,
NextDate DATETIME,
PRIMARY KEY (ID_frequency)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Article ;
CREATE TABLE Article (ID_article BIGINT AUTO_INCREMENT NOT NULL,
Pays VARCHAR,
Summary TEXT,
URL VARCHAR,
ReadingTime TIME,
PRIMARY KEY (ID_article)) ENGINE=InnoDB;

DROP TABLE IF EXISTS TVprogram ;
CREATE TABLE TVprogram (ID_TVprogram BIGINT AUTO_INCREMENT NOT NULL,
Title VARCHAR,
Synopsis TEXT,
Begin TIME,
Genre VARCHAR,
ID_channel **NOT FOUND**,
PRIMARY KEY (ID_TVprogram)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Recipe ;
CREATE TABLE Recipe (ID_recipe BIGINT AUTO_INCREMENT NOT NULL,
Name VARCHAR,
Picture VARCHAR,
NbPerson INT,
PreparationTime TIME,
CookingTime TIME,
TotalTime TIME,
Score FLOAT,
Price FLOAT,
Difficulty FLOAT,
Steps TEXT,
Ingredients TEXT,
Calories FLOAT,
ID_type **NOT FOUND**,
PRIMARY KEY (ID_recipe)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Health ;
CREATE TABLE Health (ID_health BIGINT AUTO_INCREMENT NOT NULL,
RecordDate DATE,
Weight FLOAT,
Calories FLOAT,
Sleep TIME,
ID_user **NOT FOUND**,
PRIMARY KEY (ID_health)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Sport ;
CREATE TABLE Sport (ID_sport BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
Picture VARCHAR,
Calories FLOAT,
PRIMARY KEY (ID_sport)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Muscle ;
CREATE TABLE Muscle (ID_muscle BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_muscle)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Channel ;
CREATE TABLE Channel (ID_channel BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_channel)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Type ;
CREATE TABLE Type (ID_type BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_type)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Town ;
CREATE TABLE Town (ID_town BIGINT AUTO_INCREMENT NOT NULL,
Label VARCHAR,
PRIMARY KEY (ID_town)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Work ;
CREATE TABLE Work (ID_muscle **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_sport **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_muscle,
 ID_sport)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Program ;
CREATE TABLE Program (ID_user **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_sport **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_user,
 ID_sport)) ENGINE=InnoDB;

ALTER TABLE Weather ADD CONSTRAINT FK_Weather_ID_sky FOREIGN KEY (ID_sky) REFERENCES Sky (ID_sky);

ALTER TABLE Weather ADD CONSTRAINT FK_Weather_ID_town FOREIGN KEY (ID_town) REFERENCES Town (ID_town);
ALTER TABLE User ADD CONSTRAINT FK_User_town_id_town FOREIGN KEY (town_id_town) REFERENCES Town (ID_town);
ALTER TABLE Renewal ADD CONSTRAINT FK_Renewal_ID_frequency FOREIGN KEY (ID_frequency) REFERENCES Frequency (ID_frequency);
ALTER TABLE TVprogram ADD CONSTRAINT FK_TVprogram_ID_channel FOREIGN KEY (ID_channel) REFERENCES Channel (ID_channel);
ALTER TABLE Recipe ADD CONSTRAINT FK_Recipe_ID_type FOREIGN KEY (ID_type) REFERENCES Type (ID_type);
ALTER TABLE Health ADD CONSTRAINT FK_Health_ID_user FOREIGN KEY (ID_user) REFERENCES User (ID_user);
ALTER TABLE Work ADD CONSTRAINT FK_Work_ID_muscle FOREIGN KEY (ID_muscle) REFERENCES Muscle (ID_muscle);
ALTER TABLE Work ADD CONSTRAINT FK_Work_ID_sport FOREIGN KEY (ID_sport) REFERENCES Sport (ID_sport);
ALTER TABLE Program ADD CONSTRAINT FK_Program_ID_user FOREIGN KEY (ID_user) REFERENCES User (ID_user);
ALTER TABLE Program ADD CONSTRAINT FK_Program_ID_sport FOREIGN KEY (ID_sport) REFERENCES Sport (ID_sport);
