<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    
    <title>EverydaySunshine - <?= htmlspecialchars(ucfirst($pageName)) ?></title>
    <link rel="icon" type="image/png" href="resource/image/icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="app/view/common/css/normalize.css"/><!-- memes valeurs css par defaut pour tous les navigateurs -->
    <link rel="stylesheet" href="app/view/common/css/template.css"/><!-- memes valeurs css par defaut pour tous les navigateurs -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-chJtTd1EMa6hQI40eyJWF6829eEk4oIe7b3nNtUni7VxA3uHc/uIM/8ppyjrggfV" crossorigin="anonymous"> 
    
    <?php if (file_exists(__DIR__."/../css/$pageName.css")) { ?>
        <link rel="stylesheet" href="app/view/css/<?= htmlspecialchars($pageName) ?>.css"/><!-- style de la partie section -->
    <?php } ?>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
            <a class="navbar-brand" href="index.php?page=home">Your Everyday Sunshine</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse ml-4" id="navbarSupportedContent">
                <?= $userGateContent ?>
            </div>
        </nav>
    </header>

    
    <?php if (isset($trustedPost['errMsgs'])) { ?>
        <aside>
            <ul>
                <?php foreach($trustedPost['errMsgs'] as $errMsg) { ?>
                    <li class="liste_erreurs">
                        <?= htmlspecialchars($errMsg) ?>
                    </li>
                <?php } ?>
            </ul> 
        </aside>
    <?php } ?>
    

    <section class="container-fluid">
        <?= $sectionContent ?>
    </section>


    <footer class="d-flex justify-content-center">
        <div class="p-3">
            <hr>
            <span>©2020 - YourEverydaySunshine - Crédits</span><br>
            <span>Contact : <em><a href="mailto:contact@YourEverydaySunshine.fr">contact@YourEverydaySunshine.fr</a></em></span>
        </div>
    </footer>
</body>
</html>

<!-- load js scripts after html display for performance issues -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
