<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="css/normalize.css"/><!-- memes valeurs css par defaut pour tous les navigateurs -->
    <!-- framework bootstrap : soit en local dans common/css, soit directement en ligne comme ici -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
    <link rel="stylesheet" href="css/template.css"/><!-- style de la partie template + declaration variables -->
    <?php if (file_exists("../css/<?= $pageName ?>.css")) { ?>
        <link rel="stylesheet" href="../css/<?= $pageName ?>.css"/><!-- style de la partie section -->
    <?php } ?>
    <title>AppName - <?= htmlspecialchars(ucfirst($pageName)) ?></title>
</head>

<body>
    <section>
        <?= $sectionContent ?>
    </section>
</body>

<!-- load js bootstrap framework script after html for performance issues -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
